version: "3"
services:
  github-backup:
    image: nicholas0g/github-backup
    environment:
      ORG: ${ORG}
      TOKEN: ${TOKEN}
      USER: ${USER}
      WAIT: ${WAIT}
    volumes:
      - ./backup:/app/repositories
